export const API_URL = 'http://localhost:4000';

// categories of illness as per schema
export const illnessCategories = [
    'Addiction/Substance Abuse',
    'Allergic/Immunologic',
    'Alzheimer Disease',
    'Anemia',
    'Arthritis',
    'Asthma',
    'Attention-Deficit/Hyperactivity Disorder (ADHD)',
    'Autoimmune',
    'Breast Cancer',
    'Cancer',
    'Cardiovascular',
    'Cataracts',
    'Cholera',
    'Chronic Condition',
    'Chronic Fatigue Syndrome',
    'Colon Cancer',
    'Common Cold',
    'Cystic Fibrosis',
    'Dengue',
    'Diabetes',
    'Developmental/Pediatric',
    'Eczema',
    'Endometriosis',
    'Environmental/Occupational',
    'Epilepsy',
    'Fibromyalgia',
    'Gallstones',
    'Gastritis',
    'Gastroesophageal Reflux Disease (GERD)',
    'Gastrointestinal',
    'Glaucoma',
    'Graves Disease',
    'HIV/AIDS',
    'Hepatitis',
    'Huntington\'s Disease',
    'Hypertension',
    'Infectious Disease',
    'Influenza',
    'Interstitial Cystitis',
    'Irritable Bowel Syndrome (IBS)',
    'Kidney Stones',
    'Leukemia',
    'Lung Cancer',
    'Lupus',
    'Malaria',
    'Melanoma',
    'Measles',
    'Mental Health',
    'Multiple Sclerosis',
    'Myasthenia Gravis',
    'Neurological',
    'Osteoporosis',
    'Ovarian Cancer',
    'Pancreatic Cancer',
    'Parkinson Disease',
    'Pneumonia',
    'Polycystic Ovary Syndrome (PCOS)',
    'Prostate Cancer',
    'Psoriasis',
    'Pulmonary Hypertension',
    'Rheumatoid Arthritis',
    'Sleep Disorders',
    'Sickle Cell Anemia',
    'Splenomegaly',
    'Stroke',
    'Testicular Cancer',
    'Thyroid Disorders',
    'Tuberculosis',
    'Typhoid',
    'Ulcerative Colitis',
    'Vision/Eye Disorders',
    'Other'
  ];